In [1]:
import torch
print(torch.__version__)

0.4.1


In [2]:
# 2-D tensor
tensor_array = torch.Tensor([[1,2],[4,5]])
tensor_array

tensor([[1., 2.],
        [4., 5.]])

In [3]:
tensor_uninitialized = torch.Tensor(3,3)
torch.numel(tensor_uninitialized)

9

In [4]:
tensor_initialized = torch.rand(2,3)
tensor_initialized

tensor([[0.2498, 0.8805, 0.2480],
        [0.4703, 0.7751, 0.0855]])

In [5]:
tensor_int = torch.randn(5,3).type(torch.IntTensor)
tensor_int

tensor([[ 0,  0,  0],
        [ 0,  0, -1],
        [-2,  0,  0],
        [ 0,  1, -1],
        [ 2,  0,  0]], dtype=torch.int32)

In [6]:
tensor_long = torch.LongTensor([1.0,2.0,3.0])
tensor_long

tensor([1, 2, 3])

In [7]:
tensor_byte = torch.ByteTensor([0, 261, 1, -5])
tensor_byte

tensor([  0,   5,   1, 251], dtype=torch.uint8)

In [8]:
tensor_ones = torch.ones(10)
tensor_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
tensor_zeros = torch.zeros(10,10)
tensor_zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
tensor_eye = torch.eye(3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2]])

In [13]:
tensor_ones_shape_eye = torch.ones_like(tensor_eye)
tensor_ones_shape_eye

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
initial_tensor = torch.rand(3,3)
# All in-place operations have the "_" suffix
initial_tensor.fill_(3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [17]:
# outer-place operation
new_tensor = initial_tensor.add(4)
new_tensor

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

In [19]:
initial_tensor.add_(5)
initial_tensor

tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])

In [20]:
import numpy as np

numpy_arr = np.array([1,2,3])
numpy_arr

array([1, 2, 3])

In [21]:
tensor = torch.from_numpy(numpy_arr)
tensor

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([1, 2, 3])

In [23]:
numpy_arr[1] = 4
numpy_arr

array([1, 4, 3])

In [24]:
# tensors and numpy arrays share the same memory
tensor

tensor([1, 4, 3], dtype=torch.int32)

In [25]:
numpy_from_tensor

array([1, 4, 3])

In [26]:
initial_tensor = torch.rand(2,3)
initial_tensor

tensor([[0.6526, 0.9973, 0.0069],
        [0.2294, 0.3132, 0.6700]])

In [27]:
initial_tensor[0,2]

tensor(0.0069)

In [28]:
initial_tensor[:,1:]

tensor([[0.9973, 0.0069],
        [0.3132, 0.6700]])

In [29]:
initial_tensor.size()

torch.Size([2, 3])

In [30]:
initial_tensor.shape

torch.Size([2, 3])

In [36]:
resized_tensor = initial_tensor.view(6)
resized_tensor.shape

torch.Size([6])

In [37]:
# It has same values like initial_tensor but in 1-D
resized_tensor

tensor([0.6526, 0.9973, 0.0069, 0.2294, 0.3132, 0.6700])

In [41]:
resized_tensor = initial_tensor.view(3,2)
resized_tensor

tensor([[0.6526, 0.9973],
        [0.0069, 0.2294],
        [0.3132, 0.6700]])

In [42]:
resized_matrix = initial_tensor.view(-1,2)
resized_matrix

tensor([[0.6526, 0.9973],
        [0.0069, 0.2294],
        [0.3132, 0.6700]])

In [43]:
initial_tensor

tensor([[0.6526, 0.9973, 0.0069],
        [0.2294, 0.3132, 0.6700]])

In [44]:
sorted_tensor, sorted_indices = torch.sort(initial_tensor)

In [45]:
sorted_tensor

tensor([[0.0069, 0.6526, 0.9973],
        [0.2294, 0.3132, 0.6700]])

In [46]:
sorted_indices

tensor([[2, 0, 1],
        [0, 1, 2]])

In [47]:
# dim=0 for column-based sorting
sorted_tensor, sorted_indices = torch.sort(initial_tensor, dim=0)
sorted_tensor

tensor([[0.2294, 0.3132, 0.0069],
        [0.6526, 0.9973, 0.6700]])

In [48]:
sorted_indices

tensor([[1, 1, 0],
        [0, 0, 1]])