In [2]:
# Autograd: core package for automatic differentiation -remembers all executed operations in the forward phase and replays them
# in the backward phase

import torch

In [3]:
tensor = torch.Tensor([[3, 4],
                       [7,5]])
tensor

tensor([[3., 4.],
        [7., 5.]])

In [5]:
# computations for this tensor will not be tracked by the autograd package
tensor.requires_grad

False

In [6]:
# autograd set to true
tensor.requires_grad_()

tensor([[3., 4.],
        [7., 5.]], requires_grad=True)

In [7]:
# tensor.grad -> accumulates the gradient of computations with respect to this tensor after the backward pass
# we haven't perform the backward pass yet
print(tensor.grad)

None


In [9]:
# we haven't perform the backward pass yet, there is no gradient func associated with this tensor
print(tensor.grad_fn)

None


In [11]:
out = tensor * tensor
out

tensor([[ 9., 16.],
        [49., 25.]], grad_fn=<ThMulBackward>)

In [13]:
# requires_grad true because derived from the original tensor
out.requires_grad

True

In [14]:
print(out.grad)

None


In [15]:
# but we have grad_fn. Because out is a tensor that represents the result of a computation which required gradient,
# it has a gradient function associated with it.
print(out.grad_fn)

In [16]:
print(tensor.grad_fn)

None


In [17]:
# func different because the computation is different
out = (tensor * tensor).mean()
print(out.grad_fn)

In [18]:
print(tensor.grad_fn)

None


In [19]:
out.backward()

In [20]:
# All tensors which were part of the computation of "out" now have gradients calculated
print(tensor.grad)

tensor([[1.5000, 2.0000],
        [3.5000, 2.5000]])


In [21]:
new_tensor = tensor * tensor
print(new_tensor.requires_grad)

True


In [23]:
# In NN training phase, we require gradient calculation
# we turn off the gradient when NN is running on the prediction phase
with torch.no_grad():
    new_tensor = tensor * tensor
    print("new_tensor = ", new_tensor)
    print("requires_grad for tensor = ", tensor.requires_grad)
    print("requires_grad for new_tensor = ", new_tensor.requires_grad)

new_tensor =  tensor([[ 9., 16.],
        [49., 25.]])
requires_grad for tensor =  True
requires_grad for new_tensor =  False
